num_trials: 1
planning_time_limit: 120.0
max_iterations: 100
max_iterations_after_collision_free: 0
num_trajectories: 1

smoothness_cost_weight: 0.0001
obstacle_cost_weight: 1.0
torque_cost_weight: 0.0
state_validity_cost_weight: 0.0
endeffector_velocity_cost_weight: 0.0
contact_invariant_cost_weight: 0.0
physics_violation_cost_weight: 0.0
goal_pose_cost_weight: 0.0
CoM_cost_weight: 0.0
FTR_cost_weight: 0.0
cartesian_trajectory_cost_weight: 0.0
smoothness_cost_velocity: 0.0
smoothness_cost_acceleration: 1.0
smoothness_cost_jerk: 0.0
ridge_factor: 0.0

temp: [1000.0, 1000.0, 0.0]

print_planning_info: false

animate_path: true
animate_endeffector: true
animate_endeffector_segment:
  lower_body: end_effector_link
  torso: torso_x_link
  head: head_endeffector_link
  left_arm: left_hand_endeffector_link
  right_arm: right_hand_endeffector_link
  unified_body: right_hand_endeffector_link
trajectory_duration: 5.0
trajectory_discretization: 0.05
phase_duration: 0.5
friction_coefficient: 2.0
lower_body_root: segment_0
planning_step_size: 5.0

collision_links:
  segment_0: true
  segment_1: true
  segment_2: true
  segment_3: true
  segment_4: true
  segment_5: true
  segment_6: true
  segment_7: true
  
use_cumulative_costs: true
use_smooth_noises: true

num_rollouts: 10
num_reused_rollouts: 5
noise_stddev: 2.0
noise_decay: [0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999]

num_contacts: 0
contact_variable_initial_values: [0.2, 0.2, 0.0, 0.0]
contact_variable_goal_values: [0.2, 0.2, 0.0, 0.0]

environment_model: package://kuka_description/env/monitor_full.dae
environment_model_position: [0.0, 0.0, 0.0]
environment_model_scale: 1.0



