controller_list:
  - name: fake_right_arm_controller
    joints:
      - upper_right_arm_z_joint
      - upper_right_arm_y_joint
      - upper_right_arm_x_joint
      - lower_right_arm_joint
      - right_hand_z_joint
      - right_hand_y_joint
      - right_hand_x_joint
  - name: fake_left_arm_controller
    joints:
      - upper_left_arm_z_joint
      - upper_left_arm_y_joint
      - upper_left_arm_x_joint
      - lower_left_arm_joint
      - left_hand_z_joint
      - left_hand_y_joint
      - left_hand_x_joint
  - name: fake_torso_controller
    joints:
      - torso_z_joint
      - torso_y_joint
      - torso_x_joint
  - name: fake_head_controller
    joints:
      - head_z_joint
      - head_y_joint
      - head_x_joint
  - name: fake_right_gripper_controller
    joints:
      - right_hand_endeffector_joint
  - name: fake_left_gripper_controller
    joints:
      - left_hand_endeffector_joint
  - name: fake_left_leg_controller
    joints:
      - upper_left_leg_z_joint
      - upper_left_leg_y_joint
      - upper_left_leg_x_joint
      - lower_left_leg_joint
      - left_foot_x_joint
      - left_foot_y_joint
      - left_foot_z_joint
  - name: fake_right_leg_controller
    joints:
      - upper_right_leg_z_joint
      - upper_right_leg_y_joint
      - upper_right_leg_x_joint
      - lower_right_leg_joint
      - right_foot_x_joint
      - right_foot_y_joint
      - right_foot_z_joint
  - name: fake_left_foot_controller
    joints:
      - left_foot_endeffector_joint
  - name: fake_right_foot_controller
    joints:
      - right_foot_endeffector_joint
  - name: fake_base_controller
    joints:
      - base_prismatic_joint_x
      - base_prismatic_joint_y
      - base_prismatic_joint_z
      - base_revolute_joint_x
      - base_revolute_joint_y
      - base_revolute_joint_z
  - name: fake_lower_body_controller
    joints:
      - base_prismatic_joint_x
      - base_prismatic_joint_y
      - base_prismatic_joint_z
      - base_revolute_joint_x
      - base_revolute_joint_y
      - base_revolute_joint_z
      - upper_left_leg_z_joint
      - upper_left_leg_y_joint
      - upper_left_leg_x_joint
      - lower_left_leg_joint
      - left_foot_x_joint
      - left_foot_y_joint
      - left_foot_z_joint
      - upper_right_leg_z_joint
      - upper_right_leg_y_joint
      - upper_right_leg_x_joint
      - lower_right_leg_joint
      - right_foot_x_joint
      - right_foot_y_joint
      - right_foot_z_joint
  - name: fake_whole_body_controller
    joints:
      - base_prismatic_joint_x
      - base_prismatic_joint_y
      - base_prismatic_joint_z
      - base_revolute_joint_x
      - base_revolute_joint_y
      - base_revolute_joint_z
      - torso_z_joint
      - torso_y_joint
      - torso_x_joint
      - head_z_joint
      - head_y_joint
      - head_x_joint
      - upper_left_arm_z_joint
      - upper_left_arm_y_joint
      - upper_left_arm_x_joint
      - lower_left_arm_joint
      - left_hand_z_joint
      - left_hand_y_joint
      - left_hand_x_joint
      - upper_right_arm_z_joint
      - upper_right_arm_y_joint
      - upper_right_arm_x_joint
      - lower_right_arm_joint
      - right_hand_z_joint
      - right_hand_y_joint
      - right_hand_x_joint
      - upper_left_leg_z_joint
      - upper_left_leg_y_joint
      - upper_left_leg_x_joint
      - lower_left_leg_joint
      - left_foot_x_joint
      - left_foot_y_joint
      - left_foot_z_joint
      - upper_right_leg_z_joint
      - upper_right_leg_y_joint
      - upper_right_leg_x_joint
      - lower_right_leg_joint
      - right_foot_x_joint
      - right_foot_y_joint
      - right_foot_z_joint
  - name: fake_head_top_controller
    joints:
      - head_endeffector_joint