joint_limits:
  base_prismatic_joint_x:
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: false
    max_acceleration: 0
  base_prismatic_joint_y:
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: false
    max_acceleration: 0
  base_prismatic_joint_z:
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: false
    max_acceleration: 0
  base_revolute_joint_x:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  base_revolute_joint_y:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  base_revolute_joint_z:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  head_x_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  head_y_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  head_z_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_foot_endeffector_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_foot_x_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_foot_y_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_foot_z_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_endeffector_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_x_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_y_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_z_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  lower_left_arm_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  lower_left_leg_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  lower_right_arm_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  lower_right_leg_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_foot_endeffector_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_foot_x_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_foot_y_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_foot_z_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_endeffector_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_x_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_y_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_z_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  torso_x_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  torso_y_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  torso_z_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  upper_left_arm_x_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  upper_left_arm_y_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  upper_left_arm_z_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  upper_left_leg_x_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  upper_left_leg_y_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  upper_left_leg_z_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  upper_right_arm_x_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  upper_right_arm_y_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  upper_right_arm_z_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  upper_right_leg_x_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  upper_right_leg_y_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  upper_right_leg_z_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0