sensors:
 - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
   image_topic: camera_top/depth/image_raw
   queue_size: 5
   near_clipping_plane_distance: 0.3
   far_clipping_plane_distance: 2.0
   skip_vertical_pixels: 1
   skip_horizontal_pixels: 1
   shadow_threshold: 1.0
   padding_scale: 4.0
   padding_offset: 0.04
   point_subsample: 10
